name: laundryminder
description: "Dormitory laundry status checking application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  google_fonts: ^6.1.0
  cloud_firestore: ^4.15.4
  flutter_svg: ^2.0.9
  nfc_manager: ^3.3.0
  card_loading: ^0.3.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/disabled.png
    - assets/washer.png
    - assets/dryer.png
    - assets/dryer_running.gif
    - assets/dryer_vacant.png
    - assets/washer_running.gif
    - assets/washer_vacant.png
    - assets/icons/add_new.svg
    - assets/icons/nfc_tag.png

