name: laundryminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
assets:
  - assets/

